### ISSUE TITLE
Sctipt doesn't work from today

### ISSUE THREAD

**Issue by suvalex** [nemanjan00/Badoo-Autolike#2]
I think because of the new version of Badoo.

**Comment by nemanjan00** [comment]
It still works for me

Can you provide more info about new version? Seems like they are not upgrading all users at the same time...

**Comment by BramscoChill** [comment]
The script is also not working for me. The class name of the yes button changed. When i changed this line:
document.getElementsByClassName('js-profile-header-vote b-link')[0].click();
to this line:
document.getElementsByClassName('js-profile-header-vote-yes')[0].click();

It's working again. Maybe the class name can have multiple values, depening on something. Maybe rewrite it so it can have both (or more) class names.

**Comment by nemanjan00** [comment]
Oh, sorry, I missed repo name... 

I myself use newer version. This one is not maintained anymore... 

https://github.com/nemanjan00/BadooNearbyLike

**Comment by nemanjan00** [comment]
@BramscoChill thanks for fix. 

Updated script. 

Can someone confirm if it is ok now?

**Comment by suvalex** [comment]
@nemanjan00 it's working now. 
Thank you!

**Comment by BramscoChill** [comment]
cool, its working now. Thanks
